<!--Global JS-->
<script src="https://karmamgmt.com/wecheckbetav0.1/admin/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
<script src="https://karmamgmt.com/wecheckbetav0.1/admin/assets/plugins/navgoco/jquery.navgoco.min.js"></script>
<script src="https://karmamgmt.com/wecheckbetav0.1/admin/assets/plugins/waypoints/waypoints.min.js"></script>
<script src="https://karmamgmt.com/wecheckbetav0.1/admin/assets/plugins/switchery/switchery.min.js"></script>
<script src="https://karmamgmt.com/wecheckbetav0.1/admin/assets/js/application.js"></script>
<script src="https://karmamgmt.com/wecheckbetav0.1/admin/assets/plugins/dataTables/js/jquery.dataTables.js"></script>
<script src="https://karmamgmt.com/wecheckbetav0.1/admin/assets/plugins/dataTables/js/dataTables.bootstrap.js"></script>
<script src="https://karmamgmt.com/wecheckbetav0.1/admin/assets/plugins/bootstrap-wysihtml5/js/wysihtml5-0.3.0.js"></script>
<script src="https://karmamgmt.com/wecheckbetav0.1/admin/assets/plugins/bootstrap-wysihtml5/js/bootstrap3-wysihtml5.js"></script>